branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.14.1\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\msvc2017_64\bin;%PATH%;
build_script:
  - cmake .
  - cmake --build .
after_build:
  - windeployqt testProj.exe

artifacts:
  - path: testProj.exe
  - path: .
    type: zip
