branches:
  only:
    - master

image:
  - Visual Studio 2019
  - Ubuntu
  - macOS
  

install:
  - cmd: set QTDIR=C:\Qt\5.14.1\msvc2017_64
  - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\msvc2017_64\bin;%PATH%;
  - sh: sudo apt-get update -qq
  - sh: sudo apt-get -y install build-essential
  - sh: sudo apt-get -y install qtbase5-dev libqt5opengl5-dev libgl-dev
build_script:
  - cmake . -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
after_build:
  - cmd: windeployqt release/testProj.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - sh: mkdir release
  - sh: cp testProj release
  
artifacts:
  - path: release
    type: zip         
