branches:
  only:
    - master

image:
  - macOS
  - Visual Studio 2019
  - Ubuntu
  
for:
-
  matrix:
    only:
      - image: Ubuntu
  install:
  - sudo apt-get update -qq
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install qtbase5-dev libqt5opengl5-dev libgl-dev
  after_build:
  - mkdir release
  - cp testProj release
-
  matrix:
    only:
      - image: Visual Studio 2019
  install:
  - cmd: set QTDIR=C:\Qt\5.14.1\msvc2017_64
  - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\msvc2017_64\bin;%PATH%;
  after_build:
  - windeployqt release/testProj.exe
-
  matrix:
    only:
      - image: macOS
  install:
  - export PATH="/usr/local/opt/qt/bin:$PATH"
  after_build:
  - mkdir release
  - cp testProj release
  - otool -L release/testProj
  - macdeployqt release/testProj

build_script:
  - cmake . -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  
artifacts:
  - path: release
    type: zip  
