branches:
  only:
    - master

image:
  - macOS
  - Visual Studio 2019
  - Ubuntu
  
for:
-
  matrix:
    only:
      - image: Ubuntu
  install:
  - sudo apt-get update -qq
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install qtbase5-dev libqt5opengl5-dev libgl-dev
  after_build:
  - mkdir release
  - cp testProj release
-
  matrix:
    only:
      - image: Visual Studio 2019
  install:
  - cmd: set QTDIR=C:\Qt\5.14.1\msvc2017_64
  - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\msvc2017_64\bin;%PATH%;
  after_build:
  - windeployqt release/testProj.exe
-
  matrix:
    only:
      - image: macOS
  install:
  - brew update > /dev/null
  - brew install qt5
  - chmod -R 755 /usr/local/opt/qt5/*
  - export QTDIR="/usr/local/opt/qt5"
  - export PATH="$QTDIR/bin:$PATH"
  - export QT_SELECT=qt5
  after_build:
  - mkdir release
  - cp testProj release/testProj
  - cd release
  - macdeployqt testProj -verbose=3
  - cd ..
  - pwd
  - ls
  - ls /Users/appveyor/projects/testproject/install/bin/
  - cd /Users/appveyor/projects/testproject/install/bin/
  - macdeployqt testProj -verbose=3
  - which objdump

build_script:
  - cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./install
  - cmake --build . --config Release
  - cmake --build . --config Release --target install
  
artifacts:
  - path: release
    type: zip  
