branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.14.1\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\msvc2017_64\bin;%PATH%;
build_script:
  - cmake .
  - cmake --build . --config Release
after_build:
  - windeployqt release/testProj.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\testProj.exe
  - path: release
    type: zip
