language: cpp

os:
#  - linux
  - osx
#  - windows

jobs:
  include:
#    - os: linux
#      dist: bionic
#      before_install:
#      - sudo apt-get update -qq
#      - sudo apt-get install build-essential
#      - sudo apt-get install qtbase5-dev libqt5opengl5-dev libgl-dev
#
#      script:
#        - export QT_SELECT=qt5
#        - cmake .
#        - cmake --build .
    
    - os: osx
      osx_image: xcode11.3
      before_install:
      - brew update > /dev/null
      - brew install qt5
      - chmod -R 755 /usr/local/opt/qt5/*
      - export QTDIR="/usr/local/opt/qt5"
      - export PATH="$QTDIR/bin:$PATH"
      script:
        - export QT_SELECT=qt5
        - cmake .
        - cmake --build .
        - macdeployqt testProj.app -verbose=3
        - ls
    
#    - os: windows
#      script:
#      - cmake .
#      - cmake --build .
  
