language: cpp

#os:
#  - linux
#  - osx
#  - windows

jobs:
  include:
    - os: linux
      dist: bionic
      before_install:
      - sudo apt-get update -qq
      - sudo apt-get install build-essential
      - sudo apt-get install qtbase5-dev libqt5opengl5-dev libgl-dev
      compiler:
      - clang
      - gcc
      script:
        - export QT_SELECT=qt5
        - cmake .
        - cmake --build .
    
    - os: osx
      osx_image: xcode11.3
      before_install:
      - brew install qt5
      - brew link qt5 --force
      script:
        - export PATH="/usr/local/opt/qt/bin:$PATH"
        - cmake .
        - cmake --build .
    
    - os: windows
      script:
      - choco install qt-sdk
      - cmake .
      - cmake --build .
  
