language: cpp

#os:
#  - linux
#  - osx
#  - windows

jobs:
  include:
    - os: linux
      dist: bionic
      before_install:
      - sudo apt-get update -qq
      - sudo apt-get install devscripts build-essential lintian dh-make
      - sudo apt-get install qtdeclarative5-dev qt5-default libjack-jackd2-dev
      compiler:
      - clang
      - gcc
      script:
        - cmake .
        - cmake --build .
    
    - os: osx
      osx_image: xcode11.3
      before_install:
      - brew install qt5
      - brew link qt5 --force
      script:
        - cmake .
        - cmake --build .
    
    - os: windows
      script:
      - cmake .
      - cmake --build .
  
